### ISSUE TITLE
TODO for th version 0.0.1

### ISSUE THREAD

**Issue by alexandre** [alexandre/flask-rest-template#12]
- [x] - Finish the CRUD and tests in the blueprint 'users'
- [x] - Add files to deploy on Heroku
- [x] - Create an instance to test the project on Heroku
- [x] - Update the README.md
- [x] - Close the release 0.0.1

**Comment by alexandre** [comment]
feito
